/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula_14_09;

import static java.lang.Integer.parseInt;
import java.util.Random;

/**
 *
 * @author UNIP
 */
public class jogo extends javax.swing.JFrame {

    /**
     * Creates new form jogo
     */
    public jogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDoZap = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnJogar = new javax.swing.JButton();
        lbCarta1 = new javax.swing.JLabel();
        lbCarta2 = new javax.swing.JLabel();
        proBarC1 = new javax.swing.JProgressBar();
        proBarC2 = new javax.swing.JProgressBar();
        rbMaior = new javax.swing.JRadioButton();
        rbMenor = new javax.swing.JRadioButton();
        slider = new javax.swing.JSlider();
        lbResult = new javax.swing.JLabel();
        btnJogar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        btnJogar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnJogar.setText("Jogar");
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });

        lbCarta1.setBackground(new java.awt.Color(102, 102, 102));
        lbCarta1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbCarta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCarta1.setText("50");
        lbCarta1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbCarta2.setBackground(new java.awt.Color(102, 102, 102));
        lbCarta2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbCarta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCarta2.setText("?");
        lbCarta2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        proBarC1.setValue(100);

        proBarC2.setValue(100);

        grupoDoZap.add(rbMaior);
        rbMaior.setText("Maior");
        rbMaior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMaiorActionPerformed(evt);
            }
        });

        grupoDoZap.add(rbMenor);
        rbMenor.setText("Menor");
        rbMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMenorActionPerformed(evt);
            }
        });

        slider.setMaximum(99);
        slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });

        lbResult.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbResult.setText("Jogo ruim");

        btnJogar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnJogar1.setText("Novo Jogo");
        btnJogar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(proBarC1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(lbCarta1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(rbMenor)
                            .addComponent(rbMaior))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnJogar1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbCarta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(proBarC2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(btnJogar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbMaior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbMenor))
                    .addComponent(btnJogar1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(proBarC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proBarC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCarta1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCarta2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addComponent(lbResult, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        Random rn = new Random();
        int nrSort = rn.nextInt(99);
        lbCarta2.setText(Integer.toString(nrSort));
        if(rbMaior.isSelected()){
            if(parseInt(lbCarta1.getText()) > parseInt(lbCarta2.getText()))
            {
                proBarC2.setValue(proBarC2.getValue()-10);
            }else{
                proBarC1.setValue(proBarC1.getValue()-10);
            }
        }
        if(rbMenor.isSelected()){
            if(parseInt(lbCarta1.getText()) < parseInt(lbCarta2.getText()))
            {
                proBarC2.setValue(proBarC2.getValue()-10);
            }else{
                proBarC1.setValue(proBarC1.getValue()-10);
            }
        }
        if(proBarC1.getValue() == 0){
           lbResult.setText("PArabainsh, conseguiu PERDER...");
           btnJogar.setEnabled(false);
           rbMaior.setEnabled(false);
           rbMenor.setEnabled(false);
        } else if(proBarC2.getValue() == 0) {
           lbResult.setText("Parabens, obrigação vencer isso");
           btnJogar.setEnabled(false);
           rbMaior.setEnabled(false);
           rbMenor.setEnabled(false);
        }
    }//GEN-LAST:event_btnJogarActionPerformed

    private void rbMaiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaiorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMaiorActionPerformed

    private void rbMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMenorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMenorActionPerformed

    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStateChanged
        lbCarta1.setText(""+slider.getValue());
    }//GEN-LAST:event_sliderStateChanged

    private void btnJogar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogar1ActionPerformed
        btnJogar.setEnabled(true);
        slider.setValue(50);
        rbMaior.setEnabled(true);
        rbMenor.setEnabled(true);
        proBarC1.setValue(100);
        proBarC2.setValue(100);
        lbCarta1.setText("50");
        lbCarta2.setText("?");
        lbResult.setText("Jogo muito ruim");
    }//GEN-LAST:event_btnJogar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJogar;
    private javax.swing.JButton btnJogar1;
    private javax.swing.ButtonGroup grupoDoZap;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCarta1;
    private javax.swing.JLabel lbCarta2;
    private javax.swing.JLabel lbResult;
    private javax.swing.JProgressBar proBarC1;
    private javax.swing.JProgressBar proBarC2;
    private javax.swing.JRadioButton rbMaior;
    private javax.swing.JRadioButton rbMenor;
    private javax.swing.JSlider slider;
    // End of variables declaration//GEN-END:variables
}
